import Head from "next/head";
import Principal from "@/components/Karuta/Principal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Karuta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/karuta.jpg" />
      </Head>
      <div>
        <Principal />
      </div>
    </>
  );
}
